server:
  port: 9004

spring:
  application:
    name: library-app
  redis:
    host: localhost
    port: 6379
    timeout: 10000
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: library
      time-to-live: 60000

  datasource:
    url: jdbc:mariadb://localhost:3306/jwt_database
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver